### ISSUE TITLE
Create pipelines

### ISSUE THREAD

**Issue by guilhesme23** [OrcestraGamificacao/orcbot#2]
## Description

Create pipeline to test and build the project using gitlabci.

## Tasks

- [x] Create test stage
- [x] Create build stage
- [x] Push built image to Docker Hub
